name: Validate IDP configuration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate YAML syntax
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: backstage port examples agents .github/ISSUE_TEMPLATE
          config_data: |
            extends: default
            rules:
              document-start: disable
              line-length: disable
