#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${IKS_BACKSTAGE_APP_NAME:-iks-idp}"
DETACH="${IKS_BACKSTAGE_DETACH:-0}"
COMMAND="${1:-up}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORKSPACE_DIR="$(cd "${REPO_ROOT}/.." && pwd)"
DEFAULT_RUNTIME_DIR="${WORKSPACE_DIR}/iks-backstage-runtime"
CACHE_BASE="${XDG_CACHE_HOME:-${HOME:-/tmp}/.cache}"
CACHE_RUNTIME_DIR="${CACHE_BASE}/idp-iks-lab/iks-backstage-runtime"
COMPOSE_FILE="${REPO_ROOT}/backstage/runtime/docker-compose.yaml"

resolve_runtime_dir() {
  if [ -n "${IKS_BACKSTAGE_RUNTIME_DIR:-}" ]; then
    case "${IKS_BACKSTAGE_RUNTIME_DIR}" in
      /*) printf '%s\n' "${IKS_BACKSTAGE_RUNTIME_DIR}" ;;
      *) printf '%s/%s\n' "${REPO_ROOT}" "${IKS_BACKSTAGE_RUNTIME_DIR}" ;;
    esac
    return
  fi

  if [ -d "${DEFAULT_RUNTIME_DIR}" ] || [ -w "${WORKSPACE_DIR}" ]; then
    printf '%s\n' "${DEFAULT_RUNTIME_DIR}"
    return
  fi

  printf '%s\n' "${CACHE_RUNTIME_DIR}"
}

require_compose() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    return
  fi

  if command -v docker-compose >/dev/null 2>&1; then
    return
  fi

  echo "Error: Docker Compose is required. Install Docker with Compose V2 or docker-compose." >&2
  exit 1
}

compose() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

detect_start_script() {
  if command -v node >/dev/null 2>&1; then
    (
      cd "${RUNTIME_DIR}"
      node -e "const p=require('./package.json'); process.stdout.write(p.scripts?.dev ? 'dev' : 'start')"
    )
    return
  fi

  printf 'start'
}

write_docker_config() {
  {
    cat <<'YAML'
# Local-only Backstage runtime config for Docker.
# Generated by scripts/start-backstage-docker.sh. Do not commit this file.

app:
  title: IKS Developer Portal
  baseUrl: http://localhost:3000
  listen:
    host: 0.0.0.0
    port: 3000

backend:
  baseUrl: http://localhost:7007
  listen:
    host: 0.0.0.0
    port: 7007

organization:
  name: IKS

integrations:
  github:
    - host: github.com
YAML

    if [ -n "${GITHUB_TOKEN:-}" ]; then
      cat <<'YAML'
      token: ${GITHUB_TOKEN}
YAML
    fi

    cat <<'YAML'

catalog:
  locations:
    - type: file
      target: /workspace/idp-iks-lab/backstage/catalog/locations.yaml
      rules:
        - allow:
            - Location
            - Group
            - System
            - Component
            - Template

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local
YAML
  } > "${DOCKER_CONFIG}"
}

RUNTIME_DIR="$(resolve_runtime_dir)"
RUNTIME_PARENT="$(dirname "${RUNTIME_DIR}")"
RUNTIME_NAME="$(basename "${RUNTIME_DIR}")"
DOCKER_CONFIG="${RUNTIME_DIR}/app-config.docker.local.yaml"

if [ "${COMMAND}" != "up" ] && [ "${COMMAND}" != "down" ]; then
  echo "Usage: $0 [up|down]" >&2
  exit 1
fi

echo "IKS IDP Backstage Docker runtime"
echo "Repository: ${REPO_ROOT}"
echo "Runtime:    ${RUNTIME_DIR}"

if [ "${RUNTIME_DIR}" != "${DEFAULT_RUNTIME_DIR}" ] && [ -z "${IKS_BACKSTAGE_RUNTIME_DIR:-}" ]; then
  echo "Note: ${WORKSPACE_DIR} is not writable, using cache runtime instead."
fi

require_compose

export IKS_BACKSTAGE_RUNTIME_DIR="${RUNTIME_DIR}"
export IKS_BACKSTAGE_REPO_ROOT="${REPO_ROOT}"

if [ "${COMMAND}" = "down" ]; then
  echo
  echo "Stopping Backstage Docker runtime..."
  compose -f "${COMPOSE_FILE}" -p idp-iks-lab-backstage down
  exit 0
fi

mkdir -p "${RUNTIME_PARENT}"
if [ ! -w "${RUNTIME_PARENT}" ]; then
  echo "Error: runtime parent is not writable: ${RUNTIME_PARENT}" >&2
  echo "Set IKS_BACKSTAGE_RUNTIME_DIR to a writable directory and run again." >&2
  exit 1
fi

if [ ! -d "${RUNTIME_DIR}" ]; then
  if ! command -v npx >/dev/null 2>&1; then
    echo "Error: npx is required to create the local Backstage runtime." >&2
    exit 1
  fi

  echo
  echo "Creating local Backstage runtime in ${RUNTIME_DIR}"
  echo "This first run downloads dependencies and can take several minutes."
  (
    cd "${RUNTIME_PARENT}"
    printf '%s\n' "${APP_NAME}" | npx --yes @backstage/create-app@latest --path "${RUNTIME_NAME}"
  )
fi

if [ ! -f "${RUNTIME_DIR}/package.json" ]; then
  echo "Error: ${RUNTIME_DIR} exists but does not look like a generated Backstage app." >&2
  echo "Remove or rename it, then run this script again to bootstrap a fresh runtime." >&2
  exit 1
fi

echo
echo "Writing Docker runtime config: ${DOCKER_CONFIG}"
write_docker_config

export IKS_BACKSTAGE_START_SCRIPT="${IKS_BACKSTAGE_START_SCRIPT:-$(detect_start_script)}"

echo
echo "Starting Backstage in Docker..."
echo "Frontend: http://localhost:3000"
echo "Backend:  http://localhost:7007"
echo

if [ "${DETACH}" = "1" ] || [ "${DETACH}" = "true" ]; then
  compose -f "${COMPOSE_FILE}" -p idp-iks-lab-backstage up --build -d
else
  compose -f "${COMPOSE_FILE}" -p idp-iks-lab-backstage up --build
fi
